### ISSUE TITLE
十日谈，第十日：未来已来

### ISSUE THREAD

**Issue by jayli** [jayli/jayli.github.com#10]
#### 索引
- #1 第一日：初尝禁果
- #2  第二日：科班秀才
- #3 第三日：幸福感 和 归属感
- #4 第四日：架构 和 伪架构
- #5 第五日：寻找突破
- #6 第六日：码农的宿命
- #7 第七日：伯乐与千里马
- #8 第八日：做地球上最好的UED
- #9 第九日：前端技术体系
- #10 第十日：**未来已来**

---

占坑

**Comment by zhangsheng** [comment]
原来第十天还没出来。。

**Comment by itjinkui** [comment]
这么久过去了，十日谈呢 ，求第十日 。。。

**Comment by minorpoet** [comment]
where is 第十日

**Comment by alcat2008** [comment]
小说里，最后一篇都是无声胜有声。道友也打算如此？最好把占坑两字去掉。

**Comment by wankangk1** [comment]
666 未来已来

**Comment by 95erlong** [comment]
未来已来！看的我心潮澎湃！！

**Comment by HaileHuang** [comment]
由衷得感谢作者！

**Comment by qiutian00** [comment]
好文， 勉励自己加油。
