### ISSUE TITLE
蒙台梭利的三段话

### ISSUE THREAD

**Issue by jayli** [jayli/jayli.github.com#14]
![](http://gtms03.alicdn.com/tps/i3/TB1.bSTFVXXXXaeXFXX_xzgNpXX-366-498.png)

最近在看蒙台梭利婴儿早教手册，好多观点在我们组织开发和带队过程中竟惊人的适用。人的成长自有轨迹，这个过程漫长而脆弱，极易被破坏。这个现象同时适用于小孩子和大人。小孩子心智的自我内建和大人在职业技能上的积累过程也极为类似，摘三段蒙台梭利的原话，我们一起体会一下。
#### 第一段话

> 我们注意到，所有孩子都有极力向外扩展的个性，他有主动性，他选择自己要做的事情并坚持做下去，并根据自己内在需要来改变它。他不逃避做任何努力，相反，努力探索让他们满怀喜悦的凭借自己能力克服困难。

婴儿在呀呀学步时就有着难以置信的优秀品质，这种品质甚至是很多成年人的终极追求，殊不知每个人自始就具备，只不过在漫长的成长过程中，这种品质的内建被不断打断，没有被悉心培养，以至于这种自驱动的习惯始终难以形成。

忘掉琐事，排除杂念，阅读内心，会发现这种精神胚胎一直没有熄灭。尝试点燃它吧。
#### 第二段话

> 我们将几岁大的幼儿定义为“软蜡”，意思是这时期的孩子可以加以适当的塑造，教育学家软蜡的观点没错，错就错在他们认为孩子必须由他来塑造，与此相反，孩子必须塑造他自己。因为孩子是非常能够自动自发的。而大人经常盲目的、不恰当的将孩子在自己软蜡上画出的轮廓破坏掉。

我前几年在带团队过程中就犯过这种错误，人的成长不能靠培训和“教”，而是要提供环境、指导、机会，这些才是人自我塑造和提升的土壤。

另一方面，人在做事过程中，多大程度排除干扰，直接影响自我塑造的质量。对于一线工程师来说，这是极其困难和极具挑战的，巧妙的设计自己的琐事漏斗，让琐事绕行，专注于重要事情，排除干扰，小心的推动自我提升。
#### 第三段话

> 我的方法论有两个要点：工作的组织和自由。工作组织合理能让孩子自我发展，散发能量，让孩子获得有益、从容的满足。就是在这种条件下，自由引导孩子不断完善自身行为和获得很强的纪律性，这种杰出的纪律性本身就是孩子自我培养出的一种镇定从容的品质。

自律是内心深处对守序的追求，在自律下最大限度的自由发挥，能散发出难以置信的能量。和自律的人合作真的是体验极爽极开心的事。自律的表象看似是按部就班，但内心深处有强大的动力。工对IT程师来讲，这种动力可以理解为对事务、代码、技术强烈的掌控欲。从这个角度看，这显然是推动人不断进步的动力源泉。

---EOF---

**Comment by Cooooper** [comment]
重读此文，收益匪浅！
