### ISSUE TITLE
Hybrid 里的麻烦事

### ISSUE THREAD

**Issue by jayli** [jayli/jayli.github.com#15]
![](http://gtms03.alicdn.com/tps/i3/TB1klf9FVXXXXXLXpXXEFwW4FXX-328-426.png)

前天收到了作者@鬼道 的签名书《[跨终端的Web](http://book.douban.com/subject/25909777/)》，读了@三七 的推荐序很是感慨。Web 在无线领域的爆发力才刚刚开始，但经过几年的磨砺，当下 Web 技术在新战场里依然水土不服，Web 仍艰难的在无线的跨终端的方向上寻找自己的位子。
### 达摩克利斯之剑

混合式开发（Hybrid）听上去很美好，但在互联网业务闪电更迭的压力下生存依然艰难。我们听到最多的是：
1. 这个功能什么时候发布？
2. 发布了我的手机怎么没看到？
3. View打开好慢，菊花怎么转这么久？
4. 紧急线上bug能不能一小时内修复？
5. 这个新功能可否搞个百分比的灰度？
6. 这个页面能不能拿到别的App里嵌入？

Hybrid 的目标是将 App 作为容器来承载Web的内容，网页依然是网页，尽管我们在前端框架瘦身、资源加载策略、图片压缩、menifest、localstorage方面穷尽所能的优化，Web 技术的基石所带来的瓶颈是无论如何也无法突破的：
1. HTTP 协议是应用层协议，而且是短链接，在弱网下耗时严重，是性能瓶颈罪魁祸首！
2. URL（Web 资源定位标示）在客户端中是极弱的配角，而 Web 对 URL 依赖严重，导致客户端 PageFlow 中页与页之间的传参和调用本质上基于文本、并有大量解析和反解析（外加正确性校验），极大影响性能和可用性。
3. Web 依赖于强网在线环境，但Hybrid中 H5 资源（HTML、CSS、JS、IMG等）需要缓存至客户端，但需要一套外围机制解决 H5 资源更新的问题，以消化长尾效应，并以尽可能保证弱网和离线的使用体验。

这三个问题不解决，在用户体验优先的大潮下，Hybrid 是活不下来的。Hybrid 就是前端技术的达摩克利斯之剑，会让前端工程师瞬间丢掉饭碗。
### Hybrid 中技术选型的麻烦事

要求解，首先要认清 H5（Web）和 Native 的分工
1. H5 优势：部署灵活，承载内容、引流冲量、方案试错、快速迭代、外部对接、开源
2. Native 优势：差异化服务、高性能体验、安全沙箱

所以，对于阿里多数业务来讲，核心流程和交易一定是Native来做，所以 H5 即使作为内容载体，也不是所有业务内容都适合用 H5 来做。即使使用H5，也很大程度的依赖工程化的方案。这些工程化方案往往是 Web 技术的弱项。比如静默更新、长尾效应、在线包和离线包的构建脚本、桥 等等。

桥，是我们面临的另外一个麻烦事。

桥的原理简单，但设计很难，因为桥更多是一把钥匙，让 H5 内嵌到特定的 App 中，这就极大的限制了 Web 技术的开放性和兼容性。淘宝的一个 H5 页面拿到微信里不一定能跑起来，因为两者桥协议不一致。这就要把桥协议纳入到规范中，但桥往往是和业务场景强相关的，这时就需要 Native SDK，这样 Web 的优势就更弱了。

如此看来，Hybrid 仅仅是“灾难”的开始，Web 的优势要发挥，必须冠以前提条件，而这些条件是需要前端工程师去一项项拆解的。这会强推 FE 们做跨界的事情，必须关注客户端开发、必须熟悉前后端分离、必须掌握多种编程语言。
### 小结

我们看到目前 H5 和 Native 的博弈现象，这种冲突实际上是理念冲突，因为 Native vs Web，本质上是编译性语言 vs 解释性语言，强类型语言 vs 弱类型语言，严格校验纠错 vs 松散适配兼容，集中式管理 vs 分散式管理。

从未有一个技术场景如此深入的涉及两种技术价值观的融合，从个体和闭源角度，多数人一定支持前者，但从整体和开源角度，后者则为必选，一旦走向共建和开源，技术选型就显得非常重要，原则上应当首选弱类型语言。比如天猫店铺的开放性就站在 HTML 这个极弱语言（甚至都不算编程语言）的肩上成长起来。因为，本质上讲，只有弱语言和去中心化才能降低共建门槛，而这又给我们提出了新的难题，即规则和规范设计。那么，一款App未来的开放（让第三方为 App 贡献代码，比如航旅无线的店铺），我们的架构思路和重点，应当据此有所倾斜。

---EOF---

**Comment by vincent1988** [comment]
嗯，架构的思路及背后的推手缺失很重要。
