### ISSUE TITLE
基于MVC的JavaScript Web富应用开发还有吗？

### ISSUE THREAD

**Issue by jaychang9** [jayli/jayli.github.com#20]
基于MVC的JavaScript Web富应用开发这本书还能买到吗？现在貌似绝版了么。。。。好像买作者翻译的这本书啊

**Comment by chaoren1641** [comment]
现在没必要买这本书了，看看react、vue官方网站文档就行了

**Comment by jayli** [comment]
这个要看出版社有没有再版的计划，现在不好说哦
