### ISSUE TITLE
十日谈，第九日：前端技术体系

### ISSUE THREAD

**Issue by jayli** [jayli/jayli.github.com#9]
#### 索引
- #1 第一日：初尝禁果
- #2  第二日：科班秀才
- #3 第三日：幸福感 和 归属感
- #4 第四日：架构 和 伪架构
- #5 第五日：寻找突破
- #6 第六日：码农的宿命
- #7 第七日：伯乐与千里马
- #8 第八日：做地球上最好的UED
- #9 第九日：**前端技术体系**
- #10 第十日：未来已来

---
### 第九日，前端技术体系

现在越来越感觉到前端技术需要成体系的积累，一方面可以规范我们的前端技术培训，另一方面，作为知识线索为新人做指引，省的走弯路，避免陷入奇技淫巧的深坑之中不能自拔。

之前我整理了一下“[前端技术知识结构](http://photo.weibo.com/1700082927/talbum/detail/photo_id/3390565977155118)”，罗列的比较散，但也基本表述清楚了我的观点。今年上半年也在整个研发中心组织了一次前端技术培训，对于前端技术的演化规律也有过整理，都放在了这个[ppt](http://ued.taobao.com/blog/2012/04/f2e-in-taobao/)中，希望对大家有所帮助。

概观国内前端技术界，其实我不认为和国外顶尖的前端技术有多少年差别，甚至很多方面都走在了他们前面，比如对IE6暴力式的兼容，以及各种外壳浏览器的风靡（呵呵，开玩笑哈）。唯一的美中不足是国外顶尖的前端技术难第一时间就在国内普及，可能是两方面原因，一是多数人英文底子很差，这可是个大问题啊。二是国内前端技术方面高质量的译文图书实在是少的可怜。那么……

接下来的最后一日，想了想还是留给未来吧。

ps：一直很喜欢“神曲”的插图，从“天堂篇”里摘出一张作为封面吧，呵呵。

**Comment by yingchao2** [comment]
前端技术体系里面提到的ppt（淘宝ued前端技术系列课程链接失效），老师可以把这个分享一下吗？
email：yingchao.me@gmail.com
